name: Android Production Build

on:
  push:
    branches: [main]
    paths:
      - 'mobile/android/**'
      - 'frontend/src/**'
  workflow_dispatch:
    inputs:
      deploy_to_play_store:
        description: 'Deploy to Play Store Internal Testing'
        required: true
        type: boolean
        default: false

jobs:
  build-prod:
    name: Build Android Production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Decode Keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > ${{ github.workspace }}/release.keystore

      - name: Create keystore.properties
        run: |
          cd mobile/android
          cat > keystore.properties << EOF
          keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}
          keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}
          storeFile=${{ github.workspace }}/release.keystore
          storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          EOF

      - name: Create google-services.json (if exists)
        if: ${{ secrets.GOOGLE_SERVICES_JSON != '' }}
        run: |
          cd mobile/android/app
          echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > google-services.json

      - name: Grant execute permission for gradlew
        run: chmod +x mobile/android/gradlew

      - name: Build Production Release Bundle
        run: |
          cd mobile/android
          ./gradlew bundleProdRelease --stacktrace

      - name: Build Production Release APK
        run: |
          cd mobile/android
          ./gradlew assembleProdRelease --stacktrace

      - name: Verify APK Signature
        run: |
          jarsigner -verify -verbose -certs mobile/android/app/build/outputs/apk/prod/release/app-prod-release.apk

      - name: Upload Bundle (AAB)
        uses: actions/upload-artifact@v4
        with:
          name: app-prod-release-bundle-${{ github.run_number }}
          path: mobile/android/app/build/outputs/bundle/prodRelease/app-prod-release.aab
          retention-days: 90

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-prod-release-apk-${{ github.run_number }}
          path: mobile/android/app/build/outputs/apk/prod/release/app-prod-release.apk
          retention-days: 90

      - name: Deploy to Play Store Internal Testing
        if: ${{ github.event.inputs.deploy_to_play_store == 'true' && secrets.PLAY_STORE_SERVICE_ACCOUNT != '' }}
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAY_STORE_SERVICE_ACCOUNT }}
          packageName: br.com.alcahub.app
          releaseFiles: mobile/android/app/build/outputs/bundle/prodRelease/app-prod-release.aab
          track: internal
          status: completed

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            mobile/android/app/build/outputs/apk/prod/release/app-prod-release.apk
            mobile/android/app/build/outputs/bundle/prodRelease/app-prod-release.aab
          generate_release_notes: true
          draft: false
          prerelease: false
